EIMS/Controllers/MentorController.cs
using EIMS.Models;
using EIMS.Models.DAL;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EIMS.Controllers
{
    public class MentorController : Controller
    {
        // Kishor
        MentorDAL objDAL = new MentorDAL();
        HomeDAL objDAL1 = new HomeDAL();
        // GET: Mentor
        public ActionResult Index()
        {
            return View("add");
        }
        [Rule]
        public ActionResult AssignProject()
        {
            return View("AssignProject");
        }

        public ActionResult AddTask()
        {
          //  ProjectTaskModel objModel = new ProjectTaskModel();
            InternDAL intObj = new InternDAL();
            ProjTaskDAL projObj = new ProjTaskDAL();
            ViewBag.projectList = projObj.GetProjectByMentorId(System.Web.HttpContext.Current.Session["UserName"].ToString().Substring(3)).AsEnumerable().Select(row =>
            new SelectListItem {
                Selected = false,
                Text = row.ProjectName,
                Value = row.ProjId.ToString()
            });
            ViewBag.data = intObj.GetAllPreferences().AsEnumerable().Select(row =>
                new SelectListItem
                {
                    Selected = false,
                    Text = row["PreferenceCategory"].ToString(),
                    Value = row["PreId"].ToString()
                }); 
            return View("AddTask");
        }

        public JsonResult SaveTask(ProjectTaskModel objAtt)
        {
            ProjTaskDAL objDAL = new ProjTaskDAL();
            
            return Json(objDAL.SaveAssignedTask(objAtt), JsonRequestBehavior.AllowGet);

        }
        public JsonResult PublishTask(ProjectTaskModel objAtt)
        {
            ProjTaskDAL objDAL = new ProjTaskDAL();

            return Json(objDAL.PublishTask(objAtt), JsonRequestBehavior.AllowGet);

        }
        public JsonResult DeleteTask(string taskid)
        {
            ProjTaskDAL objDAL = new ProjTaskDAL();

            return Json(objDAL.DeleteTask(taskid), JsonRequestBehavior.AllowGet);

        }

        public ActionResult GetAssignedTask(ProjectTaskModel objAtt)
        {
            ProjTaskDAL objDAL = new ProjTaskDAL();

            return Json(objDAL.GetAssignedTask(objAtt), JsonRequestBehavior.AllowGet);
        }

        public ActionResult EvaluateInterns(string mentorId)
        {
            InternDAL intObj = new InternDAL();
            ProjTaskDAL projObj = new ProjTaskDAL();
            ViewBag.projectList = projObj.GetProjectByMentorId(System.Web.HttpContext.Current.Session["UserName"].ToString().Substring(3)).AsEnumerable().Select(row =>
            new SelectListItem
            {
                Selected = false,
                Text = row.ProjectName,
                Value = row.ProjId.ToString()
            });
            ViewBag.data = intObj.GetAllPreferences().AsEnumerable().Select(row =>
                new SelectListItem
                {
                    Selected = false,
                    Text = row["PreferenceCategory"].ToString(),
                    Value = row["PreId"].ToString()
                });

            return View("EvaluateInterns");
        }

        //Kishor
        [Rule]
        public ActionResult AddMentor(MentorModel model)
        {

            ViewBag.Message = objDAL.AddMentor(model);
            ModelState.Clear();
            return View("add");
        }
        public ActionResult view(string msg)
        {

            IEnumerable<MentorModel> data = objDAL.GetAllMentor().AsEnumerable().Select(row =>
             new MentorModel
             {
                 Id = int.Parse(row["Id"].ToString()),
                 MentorId = row["MentorId"].ToString(),
                 FName = row["FName"].ToString(),
                 MName = row["MName"].ToString(),
                 LName = row["LName"].ToString(),
                 Address = row["Address"].ToString(),
                 Email = row["Email"].ToString(),
                 Contact = row["Contact"].ToString()

             });
            if (msg != "")
            {
                ViewBag.Message = msg;
            }
            return View("ViewMentors", data);
        }


        public ActionResult ViewMentor(int id, string name)
        {
            DataTable dt = objDAL.GetMentorByID(id);
            MentorModel objModel = new MentorModel();
            foreach (DataRow row in dt.Rows)
            {

                objModel.Id = int.Parse(row["Id"].ToString());
                objModel.MentorId = row["MentorId"].ToString();
                objModel.FName = row["FName"].ToString();
                objModel.MName = row["MName"].ToString();
                objModel.LName = row["LName"].ToString();
                objModel.Address = row["Address"].ToString();
                objModel.Email = row["Email"].ToString();
                objModel.Contact = row["Contact"].ToString();


            }
            return View("ViewMentor", objModel);

        }
        public ActionResult ViewPartialMentor(int id)
        {
            DataTable dt = objDAL.GetMentorByID(id);
            MentorModel objModel = new MentorModel();
            foreach (DataRow row in dt.Rows)
            {

                objModel.Id = int.Parse(row["Id"].ToString());
                objModel.MentorId = row["MentorId"].ToString();
                objModel.FName = row["FName"].ToString();
                objModel.MName = row["MName"].ToString();
                objModel.LName = row["LName"].ToString();
                objModel.Address = row["Address"].ToString();
                objModel.Email = row["Email"].ToString();
                objModel.Contact = row["Contact"].ToString();


            }
            return PartialView("ViewPartialMentor", objModel);
        }
        [Rule]
        public ActionResult EditDelete(MentorModel model, FormCollection form)
        {
            string action = form["btn"].ToString();
            ViewBag.Message = objDAL.EditDelete(model, action);
            ModelState.Clear();
            return view(ViewBag.Message);
        }
        public ActionResult EditMentorProfile (MentorModel model, FormCollection form)
        {
            string action = form["btn"].ToString();
            ViewBag.Message = objDAL.EditDelete(model, action);
            ModelState.Clear();
            return RedirectToAction("MentorDashboard", "Home");
        }


        public ActionResult assign()
        {

            ViewBag.projList = objDAL.GetMentorByProjId().AsEnumerable().Select(row =>
        new MentorModel
        {
            Id = int.Parse(row["Id"].ToString()),
            FName = row["FName"].ToString(),
            MName = row["MName"].ToString(),
            LName = row["LName"].ToString()

        });
            IEnumerable<ProjectModel> List = objDAL1.GetAllProjects().AsEnumerable().Select(row =>
            new ProjectModel
            {
                ProjId = int.Parse(row["ProjId"].ToString()),
                ProjectName = row["ProjectName"].ToString(),


            });
            ViewBag.ProjIdList = new SelectList(List, "ProjId", "ProjectName");

            return View("assign_Mentor");
        }

        public ActionResult Assign_Mentor(int Id)
        {
            ViewBag.projList = objDAL.GetMentorByProjId().AsEnumerable().Select(row =>
          new MentorModel
          {
              Id = int.Parse(row["Id"].ToString()),
              FName = row["FName"].ToString(),
              MName = row["MName"].ToString(),
              LName = row["LName"].ToString()

          });
            DataTable dt = objDAL.GetMentorByIDFromMentorModel(Id);
            MentorModel objModel = new MentorModel();

            foreach (DataRow row in dt.Rows)
            {
                objModel.Id = int.Parse(row["Id"].ToString());
                objModel.FName = row["FName"].ToString();
                objModel.MName = row["MName"].ToString();
                objModel.LName = row["LName"].ToString();

            }
            IEnumerable<ProjectModel> List = objDAL1.GetAllProjects().AsEnumerable().Select(row =>
            new ProjectModel
            {
                ProjId = int.Parse(row["ProjId"].ToString()),
                ProjectName = row["ProjectName"].ToString(),


            });
            ViewBag.ProjIdList = new SelectList(List, "ProjId", "ProjectName");


            return View("assign_Mentor", objModel);

        }

        public ActionResult AddProject_Mentor(MentorModel model)
        {
            ViewBag.projList = objDAL.GetMentorByProjId().AsEnumerable().Select(row =>
       new MentorModel
       {
           Id = int.Parse(row["Id"].ToString()),
           FName = row["FName"].ToString(),
           MName = row["MName"].ToString(),
           LName = row["LName"].ToString()

       });
            IEnumerable<ProjectModel> List = objDAL1.GetAllProjects().AsEnumerable().Select(row =>
            new ProjectModel
            {
                ProjId = int.Parse(row["ProjId"].ToString()),
                ProjectName = row["ProjectName"].ToString(),


            });
            ViewBag.ProjIdList = new SelectList(List, "ProjId", "ProjId");

            ViewBag.Message = objDAL.MentorAssign(model);
            ModelState.Clear();

            return View("AddProject_Mentor");
        }

        public ActionResult viewAssignedMentor()
        {
            return View("viewAssignedMentor");


        }
        public JsonResult MentorList()
        {
            List<MentorModel> AssignedMentor = new List<MentorModel>();
            AssignedMentor = objDAL.getAllAssignedMentorInfo();
            return Json(AssignedMentor, JsonRequestBehavior.AllowGet);
        }
        public JsonResult DisplayMentorList()
        {
            List<MentorModel> MentorList = new List<MentorModel>();

EIMS/Views/Home/Certificate.cshtml
@model EIMS.Models.CertificateModel

<div class="well" style="background-color:#5cb85c">
    <h3 class="text-center">Completion Letter</h3>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-5 col-lg-offset-1">
            @*@using (Html.BeginForm("AddProject_Mentor", "Mentor", FormMethod.Post))
                {*@
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <form id="myFormCertificate">
                   
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                       <label class = "control-label col-md-4">Intern Id </label>
                        <div class="col-md-8">
                           <div >
                               <input class = "form-control" type="text" id="txtInternId"/>
                           </div>
                           
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4">Internship Start Date</label>
                        <div class="col-md-8">
                            <div >
                                <input type="text" class="form-control" id="txtStartDate" placeholder="YYYY/MM/DD" />
                            </div>

                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4">Internship End Date</label>
                        <div class="col-md-8">
                            <div >
                                <input type="text" id="txtEndDate" class="form-control" placeholder="YYYY/MM/DD" />
                            </div>

                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-4">Performance Remarks</label>
                        <div class="col-md-8">
                            <div>
                                <textarea id="txtAreaRemarks" class="form-control" style="margin: 0px; width: 328px; height: 87px;"></textarea>
                            </div>

                        </div>
                    </div>
               
                </form>
            </div>
            @*}*@



       
            <hr />
            <div class="well">
                <button style="align-content:center" class="btn btn-success "  id="btnPrint">Print Letter</button>
                <button style="align-content:center" class="btn btn-success " id="btnCancel">Cancel</button>

            </div>
        </div>
        <div id="ptinnt"></div>
        <div id="editor"></div>
        
    </div>
</div>
@section Scripts{
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.debug.js" integrity="sha384-NaWTHo/8YCBYJ59830LTz/P4aQZK1sS0SneOgAvhsIl3zBu8r9RevNg5lHCHAuQ/" crossorigin="anonymous"></script>
<script src="~/ViewScript/Certificate.js"></script>
}

EIMS/Views/Home/Index.cshtml
@model EIMS.Models.ProjectModel

@{
    ViewBag.Title = "Project Lists";
}
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
@*<script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.min.js"></script>*@


<body>
    @if (Session["LoginCredentials"] != null)
    {

        var loginCredential = (EIMS.Models.LoginModel)Session["LoginCredentials"];
        // <div>@loginCredential.UserName</div>




    }
    @*<h2>ASTS Projects</h2>
        <hr />*@
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @if (ViewBag.Message != null)
    {
        <div class="danger"> @ViewBag.Message </div>
    }


    <div class="well">
        <a style="align-content:center" href="#" class="btn btn-success " data-toggle="modal" data-target="#myModal">Add Project</a>

    </div>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">

                    <button type="button" class="close" data-dismiss="modal">×</button>
                    <h1 class="modal-title" id="myModalLabel">Add Project</h1>
                </div>
                @*<div class="modal-body">*@
                    <form id="myForm">

                        <div class="form-group">
                            @*@Html.LabelFor(model => model.ProjectName, htmlAttributes: new { @class = "control-label col-md-2" })*@
                            <label class="control-label col-md-2">Project</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.ProjectName, new { htmlAttributes = new { @class = "form-control", @id = "txtProjName", placeholder = "Project Name" } })
                               @Html.ValidationMessageFor(model => model.ProjectName, "", new { @class = "text-danger" })
                               
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-2">Start Date</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control", @id = "txtStartDate", placeholder = "DD/MM/YY" } })
                                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                            </div>
                           
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-2">End Date</label>
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control", @id = "txtEndDate", placeholder = "DD/MM/YY" } })
                            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                            </div>
                          
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-2">Status</label>
                            <div class="col-md-10">
                               
                                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control", placeholder = "Status" } })
                                
                                
                                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                            </div>
                         </div>

</form>
                    <div style="text-align:center;display:none" id="loaderDiv">

                        <img src="~/Content/loading.gif" width="150" />

                    </div>

                @*</div>*@



                <div class="modal-footer">
                    <a href="#" class="btn btn-success" id="btnSubmit">Add Project</a>
                    <a href="#" class="btn btn-success" data-dismiss="modal">Cancel</a>

                    @*<button type="button" class="btn btn-primary" id="btnAdd" onclick="return Add();">Add</button>
                        <button type="button" class="btn btn-primary" id="btnUpdate" style="display:none;" onclick="Update();">Update</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>*@
                </div>
           </div>
        </div>
    </div>

    <div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">

                    <button type="button" class="close" data-dismiss="modal">×</button>
                    <h1 class="modal-title" id="myModalLabel">Edit Project</h1>
                </div>
                <div class="modal-body" id="myModalBodyDiv1">





                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">

                    <button type="button" class="close" data-dismiss="modal">×</button>
                    <h1 class="modal-title" id="myModalLabel">Delete Project</h1>
                </div>
                <div class="modal-body" id="myModalBodyDiv2">





                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="myModal20">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                    <h3 class="modal-title">Delete Project</h3>
                </div>
                <div class="modal-body">
                    <h4>Are you sure ? You want to delete this. </h4>

                    <div style="text-align:center;display:none" id="loaderDiv">
                        <img src="~/Content/loading.gif" width="150" />
                    </div>

                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-success" data-dismiss="modal">Cancel</a>
                    <a href="#" class="btn btn-success" onclick="DeleteProject()">Confirm</a>
                </div>

            </div>

        </div>

    </div>


    <div class="panel panel-body">

        <div class="col-md-12">
            <table class="display" id="MyDataTable">
                <thead>
                    <tr id="row_">
                        <th>
                            Project ID
                        </th>
                        <th>
                            Project Name
                        </th>
                        <th>
                            Start Date
                        </th>
                        <th>
                            End Date
                        </th>
                        <th>
                            Status
                        </th>
                        <th>

                        </th>
                        <th>

                        </th>
                        <th>

                        </th>

                    </tr>
                </thead>
                <tbody></tbody>


            </table>



        </div>


    </div>
    <input type="hidden" id="hiddenProjId" />
</body>
<script>

    $(document).ready(function () {


        ValidateSession();
        ProjectList();
        $("#btnSubmit").click(function () {

            

            var myformdata = $("#myForm").serialize();
            if (!$("#myForm").valid()) {

                return false;
            }
            $("#loaderDiv").show();

            $.ajax({

                type: "POST",
                url: "/Home/AddProject",
                data: myformdata,
                success: function () {
                    $("#loaderDiv").hide();
                    $("#myModal").modal("hide");
                    window.location.href = "/Home/Index";
                }

                })
            //}
        })


    });
    var Validation = function () {
        var name = $("#txtProjName").val();
        var startDate = $("#txtStartDate").val();
        var endDate = $("#txtEndDate").val();
        var errMsg = "";
        if (name == "") {
            errMsg += "Enter Project Name <br>";
        }
        if (startDate == "") {
            errMsg += "Enter Start Date  <br>";
        }
        if (endDate == "") {
            errMsg += "Enter End Date <br>";
        }
        if (errMsg != "")
        {
            $.alert({
                title: 'Alert',
                content: errMsg,
                animation: 'none',
                type: 'dark'

            });
            return false;
        }
        else {
            return true;
        }

    }
        var ProjectList = function () {

            $.ajax({

                type: "Get",
                url: "/Home/ProjectList",
                success: function (response) {

                    BindDataTable(response);

                }
            })

        }


        var BindDataTable = function (response) {

            $("#MyDataTable").DataTable({

                "aaData": response,
                "aoColumns": [

                    { "mData": "ProjId" },
                    {
                        "mData": "ProjectName"
                        
                    },
                    {
                        "mData": "StartDate"
                        },

                    { "mData": "EndDate" },
                    { "mData": "Status" },
                    {
                        "mData": "ProjId",
                        "render": function (ProjId, type, full, meta) {

                            return '<a href="#" onclick="ProjectInfo(' + ProjId + ')"><i class="glyphicon glyphicon-eye-open"></i></a>'

                        }
                    },

                      {
                          "mData": "ProjId",
                          "render": function (ProjId, type, full, meta) {

                              return '<a href="#" onclick="AddEditProject(' + ProjId + ')"><i class="glyphicon glyphicon-pencil"></i></a>'

                          }



                      },
                       {
                           "mData": "ProjId",
                           "render": function (ProjId, type, full, meta) {

                               return '<a href="#" onclick="Delete(' + ProjId + ')"><i class="glyphicon glyphicon-trash"></i></a>'

                           }



                       },



                ],
                columnDefs: [{
                    targets: [2,3], render: function (data) {
                        return moment(data).format('MMMM Do YYYY');
                    }
                }]

            });
        }
        var ProjectInfo = function (ProjId) {

           // $("#myModal1").modal("show");
           // var url = "/Home/ProjectInfo?ProjId=" + ProjId;
            $.ajax({

                type: "POST",
                url: "/Home/ProjectInfo",
               data: { ProjId:ProjId },
                success: function () {
                    window.location.href = "/Home/ProjectInfo?ProjId=" + ProjId;

                }

            })



        }
        var AddEditProject = function (ProjId) {

            var url = "/Home/AddEditProject?ProjId=" + ProjId;

            $("#myModalBodyDiv1").load(url, function () {
                $("#myModal1").modal("show");

            })

        }
        var Delete = function (ProjId) {

            var url = "/Home/Delete?ProjId=" + ProjId;

            $("#myModalBodyDiv2").load(url, function () {
                $("#myModal2").modal("show");

            })

        }

        var DeleteProject = function () {

            $("#loaderDiv").show();

            var pId = $("#hiddenProjId").val();




            $.ajax({

                type: "POST",
                url: "/Home/Delete",
                data: { ProjId: pId },
                success: function (message) {
                    $("#loaderDiv").hide();
                    $("#myModal2").modal("hide");

                }

            })

        }


</script>

@*<script>
        $(document).ready(function () {

            // $("#MyDataTable").DataTable()
            ProjectList();
        })
            var ProjectList = function () {
                $.ajax({
                    type: "Get",
                    url: "/Home/ProjectList",
                    contentType: "application/json;charset=utf-8",
                    dataType: "json",
                    success: function (response) {
                        BindDataTable(response);
                    }
                })
            }
            var BindDataTable = function (response) {
                $("MyDataTable").DataTable({
                    "aaData": response,
                    "aoColumns": [
                        { "mData": "ProjId" },
                        { "mData": "ProjectName" },
                        { "mData": "StartDate" },
                        { "mData": "EndDate" },

                    ]
                });
            }

    </script>*@

EIMS/Views/Home/MentorDashboard.cshtml
@model EIMS.Models.MentorModel

@{
    ViewBag.Title = "ViewMentor";
}
<h4>My Profile</h4>

@using (Html.BeginForm("EditMentorProfile", "Mentor", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Id)

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MentorId, htmlAttributes: new { @class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.MentorId, new { htmlAttributes = new { @class = "form-control",  @disabled = "true" } })
                @Html.ValidationMessageFor(model => model.MentorId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div id="enableFields">
            <div class="form-group">
                @Html.LabelFor(model => model.FName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FName, new { htmlAttributes = new { @class = "form-control", @disabled = "true" } })
                    @Html.ValidationMessageFor(model => model.FName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MName, new { htmlAttributes = new { @class = "form-control", @disabled = "true" } })
                    @Html.ValidationMessageFor(model => model.MName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LName, new { htmlAttributes = new { @class = "form-control", @disabled = "true" } })
                    @Html.ValidationMessageFor(model => model.LName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", @disabled = "true" } })
                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @disabled = "true" } })
                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Contact, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Contact, new { htmlAttributes = new { @class = "form-control", @disabled = "true" } })
                    @Html.ValidationMessageFor(model => model.Contact, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group well">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="Edit" id="btnEdit" name="btn" class="btn btn-success" />
                <input type="submit" value="Save" id="btnSave" name="btn" class="btn btn-success" disabled="disabled" />
              
            </div>
        </div>
    </div>
}







@section scripts{    
<script src="~/ViewScript/MentorDashboard.js"></script>
    }